/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.uva.eii.ds.empresaX.interfaz.paresVistaControl.dependiente;

/**
 *
 * @author david
 */
public class VistaRegistrarVentaDirecta extends javax.swing.JFrame {
    
    private CtrlVistaRegistrarVentaDirecta c;

    /**
     * Creates new form VistaRegistrarVentaDirecta
     */
    public VistaRegistrarVentaDirecta(CtrlVistaRegistrarVentaDirecta control) {
        c = control;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        codigoProducto = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        infoNombreProducto = new javax.swing.JLabel();
        infoPrecioVenta = new javax.swing.JLabel();
        infoSubtotal = new javax.swing.JLabel();
        infoTotal = new javax.swing.JLabel();
        btnAniadirLineaVenta = new javax.swing.JButton();
        btnNuevaLineaVenta = new javax.swing.JButton();
        btnFinalizarSinFactura = new javax.swing.JButton();
        btnFinalizarConFactura = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        info = new javax.swing.JLabel();
        cantidad = new javax.swing.JFormattedTextField();
        infoCUTramitarPago = new javax.swing.JLabel();
        infoCUGenerarFactura = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre producto:");

        jLabel2.setText("Precio venta:");

        jLabel3.setText("Subtotal:");

        jLabel4.setText("Total:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Registrar venta directa");

        jLabel6.setText("Codigo del producto");

        jLabel7.setText("Cantidad");

        infoNombreProducto.setText(" ");

        infoPrecioVenta.setText(" ");

        infoSubtotal.setText(" ");

        infoTotal.setText(" ");

        btnAniadirLineaVenta.setText("Añadir linea venta");
        btnAniadirLineaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAniadirLineaVentaActionPerformed(evt);
            }
        });

        btnNuevaLineaVenta.setText("Nueva linea \nventa");
        btnNuevaLineaVenta.setEnabled(false);

        btnFinalizarSinFactura.setText("Finalizar sin factura");
        btnFinalizarSinFactura.setEnabled(false);
        btnFinalizarSinFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarSinFacturaActionPerformed(evt);
            }
        });

        btnFinalizarConFactura.setText("Finalizar con factura");
        btnFinalizarConFactura.setEnabled(false);
        btnFinalizarConFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarConFacturaActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        info.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        info.setForeground(new java.awt.Color(255, 0, 0));
        info.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        info.setText(" ");

        cantidad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        infoCUTramitarPago.setText(" ");

        infoCUGenerarFactura.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoSubtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoPrecioVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(112, 112, 112))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoNombreProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAniadirLineaVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnNuevaLineaVenta)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnFinalizarSinFactura)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnFinalizarConFactura)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(infoCUTramitarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(infoCUGenerarFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(info)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAniadirLineaVenta)
                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(infoNombreProducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(infoPrecioVenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(infoSubtotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(infoTotal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnFinalizarSinFactura, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFinalizarConFactura, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNuevaLineaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(infoCUTramitarPago)
                    .addComponent(infoCUGenerarFactura))
                .addGap(5, 5, 5)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        c.procesarEventoSalir();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnFinalizarSinFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarSinFacturaActionPerformed
        c.procesarSinFactura();
    }//GEN-LAST:event_btnFinalizarSinFacturaActionPerformed

    private void btnFinalizarConFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarConFacturaActionPerformed
        c.procesarConFactura();
    }//GEN-LAST:event_btnFinalizarConFacturaActionPerformed

    private void btnAniadirLineaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAniadirLineaVentaActionPerformed
        c.procesarAñadirLinea();
    }//GEN-LAST:event_btnAniadirLineaVentaActionPerformed


    void ocultar() {
        this.setVisible(false);
        System.exit(0);
    }

    void mostrar() {
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAniadirLineaVenta;
    private javax.swing.JButton btnFinalizarConFactura;
    private javax.swing.JButton btnFinalizarSinFactura;
    private javax.swing.JButton btnNuevaLineaVenta;
    private javax.swing.JButton btnSalir;
    private javax.swing.JFormattedTextField cantidad;
    private javax.swing.JTextField codigoProducto;
    private javax.swing.JLabel info;
    private javax.swing.JLabel infoCUGenerarFactura;
    private javax.swing.JLabel infoCUTramitarPago;
    private javax.swing.JLabel infoNombreProducto;
    private javax.swing.JLabel infoPrecioVenta;
    private javax.swing.JLabel infoSubtotal;
    private javax.swing.JLabel infoTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables

    public String getCodigoProducto() {
        return codigoProducto.getText();
    }

    public String getCantidad() {
        return cantidad.getText();
    }

    void mostrarErrorCamposVacios() {
        info.setText("Error en alguno de los campos de entrada");
    }

    void mostrarNombreProducto(String nombreProducto) {
        infoNombreProducto.setText(nombreProducto);
    }

    void mostrarPrecioVenta(float precio) {
        infoPrecioVenta.setText(""+precio);
    }

    void mostrarSubtotal(float subtotal) {
        infoSubtotal.setText(""+subtotal);
    }

    void mostrarErrorNoExisteProducto() {
        info.setText("No existe un producto con el codigo indicado");
    }

    void mostrarErrorExistenciasEscasas() {
        info.setText("Existencias del producto escasas");
    }

    void mostrarTotal(float total) {
        infoTotal.setText(""+total);
    }

    void mostrarTramitarPago() {
        infoCUTramitarPago.setText("CU Tramitar pago realizado");
    }

    void mostrarGenerarFactura() {
        infoCUGenerarFactura.setText("CU Generar factura realizado");
    }

    void permitirNuevaLineaYFinalizar() {
        btnNuevaLineaVenta.setEnabled(true);
        btnFinalizarConFactura.setEnabled(true);
        btnFinalizarSinFactura.setEnabled(true);
    }
}
