/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.uva.eii.ds.empresaX.interfaz.paresVistaControl.operario;

import es.uva.eii.ds.empresaX.interfaz.paresVistaControl.operario.ControlVistaModificarLotes;
import es.uva.eii.ds.empresaX.negocio.modelos.Lote;
import java.util.ArrayList;

/**
 *
 * @author Jorge
 */
public class VistaModificarLotes extends javax.swing.JFrame {
    
    private ControlVistaModificarLotes cvml;
    private ArrayList<Lote> lotes;

    /**
     * Creates new form VistaModificarLotes
     */
    public VistaModificarLotes(ControlVistaModificarLotes cvml) {
        this.cvml = cvml;
        initComponents();
        despLotes.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        estadoActualLote.setVisible(false);
        nuevoEstado.setVisible(false);
        actualizarEstado.setVisible(false);
    }
    
    public void ocultar(){
        this.setVisible(false);
    }
    
    public void mostrar(){
        this.setVisible(true);
    }
    
    public void mostrarLotes(ArrayList<Lote> lotes){
        this.lotes = lotes;
        for(int i = 0; i < lotes.size(); i++){
            despLotes.addItem("Id: "+lotes.get(i).getId()+" planta: "+lotes.get(i).getPlanta());
        }
        despLotes.setVisible(true);
    }
    
    public void errorProductoNoExiste(){
        info.setText("El producto no existe");
    }
    
    public void errorNoHayLotes(){
        info.setText("No hay Lotes disponibles");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        buscar = new javax.swing.JButton();
        nombrePlanta = new javax.swing.JTextField();
        panelInfo = new javax.swing.JPanel();
        actualizarEstado = new javax.swing.JButton();
        nuevoEstado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        estadoActualLote = new javax.swing.JLabel();
        despLotes = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        info = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Modificar lotes");

        jLabel2.setText("Nombre de la Planta: ");

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        nombrePlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrePlantaActionPerformed(evt);
            }
        });

        actualizarEstado.setText("Actualiza estado");
        actualizarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarEstadoActionPerformed(evt);
            }
        });

        nuevoEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoEstadoActionPerformed(evt);
            }
        });

        jLabel4.setText("Nuevo estado:");

        despLotes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lote" }));
        despLotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                despLotesActionPerformed(evt);
            }
        });

        jLabel3.setText("Estado actual: ");

        javax.swing.GroupLayout panelInfoLayout = new javax.swing.GroupLayout(panelInfo);
        panelInfo.setLayout(panelInfoLayout);
        panelInfoLayout.setHorizontalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(estadoActualLote, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nuevoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(despLotes, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(actualizarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInfoLayout.setVerticalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoLayout.createSequentialGroup()
                .addComponent(despLotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nuevoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(estadoActualLote, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29)
                .addComponent(actualizarEstado)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(nombrePlanta)
                        .addGap(30, 30, 30)
                        .addComponent(buscar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombrePlanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        info.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombrePlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrePlantaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrePlantaActionPerformed

    private void nuevoEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoEstadoActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
       info.setText("");
       cvml.procesaBuscarPlanta();
    }//GEN-LAST:event_buscarActionPerformed

    private void despLotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_despLotesActionPerformed
        if(!despLotes.getSelectedItem().equals("Lote")){
            jLabel3.setVisible(true);
            jLabel4.setVisible(true);
            estadoActualLote.setVisible(true);
            estadoActualLote.setText(""+lotes.get(despLotes.getSelectedIndex()-1).getEstado());
            nuevoEstado.setVisible(true);
            actualizarEstado.setVisible(true);
        }else{
            jLabel3.setVisible(false);
            jLabel4.setVisible(false);
            estadoActualLote.setVisible(false);
            nuevoEstado.setVisible(false);
            actualizarEstado.setVisible(false);
        }
    }//GEN-LAST:event_despLotesActionPerformed

    private void actualizarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarEstadoActionPerformed
        cvml.procesaEventoActualizarLote();
    }//GEN-LAST:event_actualizarEstadoActionPerformed

    public String getNombrePlanta(){
        return nombrePlanta.getText();
    }
    
    public Lote getLoteSeleccionado(){
        return lotes.get(despLotes.getSelectedIndex()-1);
    }
    
    public void actualizadoConExito(int estado){
        info.setText("El lote fue actualizado al estado: "+estado+" con exito");
        nuevoEstado.setText("");
    }
    
    public String getNuevoEstado(){
        return nuevoEstado.getText();
    }
    
    public void nombreVacio(){
        info.setText("Introduzca un nombre!");
    }
    
    public void estadoVacio(){
        info.setText("Introduzca el nuevo estado!");
    }
    
    public void estadoErroneo(){
        info.setText("El estado es erroneo");
    }
    
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarEstado;
    private javax.swing.JButton buscar;
    private javax.swing.JComboBox<String> despLotes;
    private javax.swing.JLabel estadoActualLote;
    private javax.swing.JLabel info;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombrePlanta;
    private javax.swing.JTextField nuevoEstado;
    private javax.swing.JPanel panelInfo;
    // End of variables declaration//GEN-END:variables
}
